# Generated by Django 3.2.21 on 2023-10-05 17:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False, verbose_name='Código de barra')),
                ('product', models.CharField(max_length=255, verbose_name='Produto/Serviço')),
                ('unitary_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Preço unitário')),
                ('commission', models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Comissão')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ['product', 'unitary_price', 'commission'],
            },
        ),
    ]
